TIMEOUT=0

:NOTYVOS
    PROTOCOL=limine
    KERNEL_PATH=boot():/boot/notyvos-kernel.elf
    MODULE_PATH=boot():/boot/initramfs.tar
    MODULE_PATH=boot():/boot/init.elf
    MODULE_PATH=boot():/boot/PS3UPDAT.PUP