# Cross-toolchain for the NOTYVOS kernel.
# Target triple: x86_64-unknown-none-elf  (freestanding, no host libc)

set(CMAKE_SYSTEM_NAME      Generic)
set(CMAKE_SYSTEM_PROCESSOR x86_64)

set(NOTYVOS_TARGET_TRIPLE "x86_64-unknown-none-elf")

find_program(NOTYVOS_CLANG   NAMES clang   REQUIRED)
find_program(NOTYVOS_CLANGXX NAMES clang++ REQUIRED)
find_program(NOTYVOS_LLD     NAMES ld.lld  REQUIRED)
find_program(NOTYVOS_OBJCOPY NAMES llvm-objcopy REQUIRED)
find_program(NOTYVOS_AR      NAMES llvm-ar REQUIRED)

set(CMAKE_C_COMPILER   "${NOTYVOS_CLANG}"   CACHE FILEPATH "" FORCE)
set(CMAKE_CXX_COMPILER "${NOTYVOS_CLANGXX}" CACHE FILEPATH "" FORCE)
set(CMAKE_ASM_COMPILER "${NOTYVOS_CLANG}"   CACHE FILEPATH "" FORCE)

set(CMAKE_C_COMPILER_TARGET   "${NOTYVOS_TARGET_TRIPLE}")
set(CMAKE_CXX_COMPILER_TARGET "${NOTYVOS_TARGET_TRIPLE}")
set(CMAKE_ASM_COMPILER_TARGET "${NOTYVOS_TARGET_TRIPLE}")

set(CMAKE_LINKER      "${NOTYVOS_LLD}")
set(CMAKE_OBJCOPY     "${NOTYVOS_OBJCOPY}")
set(CMAKE_AR          "${NOTYVOS_AR}")

set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
